export const operationsDesignCommonPaths: string[] = [
    "Design foundation request: area lead `AGENT.md` -> role `roles/product-designer.role.md` -> skills `skills/design-system/SKILL.md`, `skills/accessibility/SKILL.md` and `skills/user-flow-mapping/SKILL.md` -> playbook `playbooks/design-foundation.playbook.md`.",
    "Product UI Spec request: area lead `AGENT.md` -> role `roles/product-designer.role.md` -> skill `skills/product-ui-spec/SKILL.md` -> playbook `playbooks/product-ui-spec-readiness.playbook.md` -> `knowledge/product-ui-spec.md`.",
    "Screen readiness request: area lead `AGENT.md` -> role `roles/product-designer.role.md` -> skill `skills/screen-specification/SKILL.md` -> playbook `playbooks/screen-readiness.playbook.md` -> `../product-ops/knowledge/implementation-packets/<feature-slug>/design/screen-specs/<screen-slug>.md`.",
    "Component readiness request: area lead `AGENT.md` -> role `roles/product-designer.role.md` -> skill `skills/component-analysis/SKILL.md` -> playbook `playbooks/component-readiness.playbook.md` -> `../product-ops/knowledge/implementation-packets/<feature-slug>/design/component-specs/<component-slug>.md`.",
    "Research request: area lead `AGENT.md` -> role `roles/ux-researcher.role.md` -> skill `skills/user-research/SKILL.md` -> playbook `playbooks/user-research.playbook.md`.",
    "Accessibility request: area lead `AGENT.md` -> role `roles/accessibility-specialist.role.md` -> skills `skills/accessibility/SKILL.md` and `skills/design-review/SKILL.md` when general UX evaluation is needed -> playbook `playbooks/accessibility-review.playbook.md`.",
    "UX writing request: area lead `AGENT.md` -> role `roles/ux-writer.role.md` -> skill `skills/microcopy/SKILL.md` -> playbook `playbooks/ux-writing.playbook.md`.",
    "Design review request: area lead `AGENT.md` -> role `roles/product-designer.role.md` or applicable specialist -> skill `skills/design-review/SKILL.md` -> output findings without creating a review playbook."
  ];
