import type { PlaybookDefinition } from "../../../../types.js";

export const strategyProductPlaybooks: PlaybookDefinition[] = [
    {
      slug: "idea-calibration",
      title: "Idea Calibration",
      purpose: "Calibrate any founder idea against the current estágio de negócio, from first seed idea to product-operating change, without jumping into roadmap, MVP backlog or implementation.",
      inputs: ["../../../leanos.yaml", "../knowledge/brief.md", "../knowledge/problem.md", "../knowledge/icp.md", "../knowledge/value-proposition.md", "../knowledge/positioning.md", "../knowledge/validation-notes.md", "../../business/knowledge/business-model-canvas.md"],
      steps: ["Carregue o AGENT de Product e escolha Product Strategist ou Product Manager.", "Use `skills/business-baseline/SKILL.md` primeiro para ler `leanos.yaml`, contexto ativo de Strategy, estágio de negócio e lacunas de Strategy Baseline.", "Se faltarem missão, princípio, modelo de receita, canal, modelo de entrega, limite de promessa ou colaboração founder/IA e isso bloquear a baseline, roteie para `../../business/playbooks/business-foundation.playbook.md` antes de consolidar Product Core.", "Escolha o caminho de calibração pelo estágio de negócio: `seed` ou `strategy_forming` constrói baseline; `mvp_shaping` compara com Escopo de Validação do MVP; `mvp_building` protege o foco de delivery atual; `mvp_live_learning` verifica sinais de aprendizado; `product_operating` e `growth_scaling` avaliam fit com produto, clientes, roadmap, riscos e timing existentes.", "Faça apenas as perguntas de discovery necessárias para amadurecer a ideia para o estágio de negócio atual.", "Use `skills/product-core/SKILL.md` quando houver sinal suficiente para consolidar produto, usuário primário, problema central, promessa, diferenciação e suposição mais arriscada.", "Avalie fit, suposições, evidência, impacto no MVP e impacto no roadmap dentro deste playbook quando a ideia afetar um MVP, produto, roadmap, sinal de cliente ou cadência operacional existente.", "Roteie decisões de pricing, receita, canal ou modelo de delivery para `../../business/skills/business-model/SKILL.md` apenas quando bloquearem a decisão de Product.", "Separe fatos, suposições, perguntas abertas e decisões do founder.", "Apresente a ideia calibrada com leitura do estágio de negócio atual, Product Core, avaliação de fit e menor próxima rota segura.", "Peça ao founder para confirmar, corrigir ou continuar calibrando antes de escrever arquivos de knowledge.", "Depois da confirmação, escolha a ponte pelo estágio de negócio: `seed`, `strategy_forming` ou `mvp_shaping` -> `playbooks/mvp-validation-scope.playbook.md`; `mvp_building` ou `mvp_live_learning` -> `activation_required: operations.product-ops`; `product_operating` ou `growth_scaling` -> `../../roadmap/playbooks/roadmap-cycle-planning.playbook.md`. Use uma nota de validação quando a ideia não estiver pronta. Não crie roadmap, Epics, Features ou escopo de delivery aqui."],
      guidedConversation: ["Faça uma pergunta útil por vez, ligada à maior lacuna de Strategy Baseline ou fit do estágio de negócio atual.", "Não aceite entrevista aberta como padrão; ofereça opções numeradas quando o founder precisar decidir.", "Evite fadiga de entrevista; não force toda skill quando a ideia já estiver clara o bastante.", "Não trate toda nova ideia como MVP quando o negócio já está construindo, validando, operando ou escalando.", "Use escolhas numeradas para lacunas previsíveis de usuário, problema, promessa, receita, canal, princípio, limite de promessa e modelo operacional.", "Peça resposta por número; se o founder responder em texto, mapeie para a opção mais próxima e confirme a interpretação.", "Termine com uma pergunta clara de confirmação antes de atualizar arquivos."],
      outputs: ["Leitura do estágio de negócio atual", "Resumo da ideia calibrada", "Avaliação de fit", "Proposta de Strategy Baseline ou recomendação de product-fit", "Fatos conhecidos", "Suposições", "Perguntas abertas", "Próxima rota recomendada"],
      filesToUpdate: ["../knowledge/brief.md", "../knowledge/problem.md", "../knowledge/icp.md", "../knowledge/value-proposition.md", "../knowledge/positioning.md", "../knowledge/validation-notes.md"]
    },
    {
      slug: "mvp-validation-scope",
      title: "Escopo de Validação do MVP",
      purpose: "Transformar uma Strategy Baseline confirmada no menor escopo de validação do MVP antes do planejamento de delivery de Product Ops.",
      inputs: ["../knowledge/brief.md", "../knowledge/problem.md", "../knowledge/icp.md", "../knowledge/value-proposition.md", "../../business/knowledge/business-model-canvas.md", "../knowledge/mvp-validation-scope.md", "../knowledge/validation-notes.md"],
      steps: ["Carregue a Strategy Baseline confirmada a partir do knowledge de Product.", "Use `skills/mvp-validation-scope/SKILL.md` para identificar a primeira tese de negócio a validar.", "Escolha o menor artefato de validação: slice de produto, landing page, workflow manual/concierge, protótipo ou automação simples.", "Separe Dentro do Escopo, Fora do Escopo, Partes Manuais / Concierge e Partes Productizadas.", "Defina Sinais de Sucesso e Sinais de Pivot.", "Rascunhe a Sequência de Validação do MVP sem criar roadmap, Epics, Features, issues do GitHub ou trabalho de implementação.", "Use `skills/coherence/SKILL.md` antes de propor atualizações de arquivo.", "Peça ao founder para confirmar o escopo de validação do MVP antes de escrever.", "Depois da confirmação, ofereça o handoff para Product Ops quando o founder quiser escopo de delivery ou planejamento de Epic."],
      guidedConversation: ["Comece reafirmando a Strategy Baseline confirmada.", "Peça apenas restrições ausentes ou escolhas de validação.", "Quando o founder quiser velocidade, prefira o menor artefato capaz de ensinar algo real ao negócio.", "Deixe o handoff explícito: Strategy valida o que deve ser tentado; Product Ops transforma escopo confirmado em trabalho de delivery."],
      outputs: ["Escopo de Validação do MVP", "Tese de negócio", "MVP slice", "Sinais de sucesso", "Sinais de pivot", "Sequência de Validação do MVP", "Recomendação de handoff para Product Ops"],
      filesToUpdate: ["../knowledge/mvp-validation-scope.md", "../knowledge/validation-notes.md"]
    }
  ];
