import type { PlaybookDefinition } from "../../../../types.js";

export const strategyProductPlaybooks: PlaybookDefinition[] = [
    {
      slug: "idea-calibration",
      title: "Idea Calibration",
      purpose: "Calibrate any founder idea against the current business stage, from first seed idea to product-operating change, without jumping into roadmap, MVP backlog or implementation.",
      inputs: ["../../../leanos.yaml", "../knowledge/brief.md", "../knowledge/problem.md", "../knowledge/icp.md", "../knowledge/value-proposition.md", "../knowledge/positioning.md", "../knowledge/validation-notes.md", "../../business/knowledge/business-model-canvas.md"],
      steps: ["Load the Product AGENT and choose Product Strategist or Product Manager.", "Use `skills/business-baseline/SKILL.md` first to read `leanos.yaml`, active Strategy context, business stage and Strategy Baseline gaps.", "Choose the calibration path from the business stage: `seed` or `strategy_forming` builds baseline; `mvp_shaping` compares against MVP Validation Scope; `mvp_building` protects current delivery focus; `mvp_live_learning` checks learning signals; `product_operating` and `growth_scaling` evaluate fit with existing product, customers, roadmap, risks and timing.", "Ask only the discovery questions needed to mature the idea for the current business stage.", "Use `skills/product-core/SKILL.md` when there is enough signal to consolidate product, primary user, core problem, promise, differentiation and riskiest assumption.", "Evaluate fit, assumptions, evidence, MVP impact and roadmap impact inside this playbook when the idea affects an existing MVP, product, roadmap, customer signal or operating cadence.", "Route pricing, revenue, channel or delivery-model decisions to `../../business/skills/business-model/SKILL.md` only when they block the Product decision.", "Separate facts, assumptions, open questions and founder decisions.", "Present the calibrated idea with current business-stage reading, Product Core, fit assessment and smallest safe next route.", "Ask the founder to confirm, correct or keep calibrating before writing knowledge files.", "After confirmation, choose the bridge by business stage: `seed`, `strategy_forming` or `mvp_shaping` -> `playbooks/mvp-validation-scope.playbook.md`; `mvp_building` or `mvp_live_learning` -> `activation_required: operations.product-ops`; `product_operating` or `growth_scaling` -> `../../roadmap/playbooks/roadmap-cycle-planning.playbook.md`. Use a validation note when the idea is not ready. Do not create roadmap, Epics, Features or delivery scope here."],
      guidedConversation: ["Ask one useful question at a time, tied to the biggest Strategy Baseline or fit gap for the current business stage.", "Avoid interview fatigue; do not force every skill when the idea is already clear enough.", "Do not treat every new idea as MVP when the business is already building, validating, operating or scaling.", "Use numbered choices only when they make the founder's decision easier.", "Let the founder answer with a number or free-form text.", "End with a clear confirmation question before file updates."],
      outputs: ["Current business-stage reading", "Calibrated idea summary", "Fit assessment", "Strategy Baseline proposal or product-fit recommendation", "Known facts", "Assumptions", "Open questions", "Recommended next route"],
      filesToUpdate: ["../knowledge/brief.md", "../knowledge/problem.md", "../knowledge/icp.md", "../knowledge/value-proposition.md", "../knowledge/positioning.md", "../knowledge/validation-notes.md"]
    },
    {
      slug: "mvp-validation-scope",
      title: "MVP Validation Scope",
      purpose: "Turn a confirmed Strategy Baseline into the smallest MVP validation scope before Product Ops delivery planning.",
      inputs: ["../knowledge/brief.md", "../knowledge/problem.md", "../knowledge/icp.md", "../knowledge/value-proposition.md", "../../business/knowledge/business-model-canvas.md", "../knowledge/mvp-validation-scope.md", "../knowledge/validation-notes.md"],
      steps: ["Load the confirmed Strategy Baseline from Product knowledge.", "Use `skills/mvp-validation-scope/SKILL.md` to identify the first business thesis to validate.", "Choose the smallest validation artifact: product slice, landing page, manual/concierge workflow, prototype or simple automation.", "Separate In Scope, Out of Scope, Manual / Concierge Parts and Productized Parts.", "Define Success Signals and Pivot Signals.", "Draft the MVP Validation Sequence without creating roadmap, Epics, Features, GitHub issues or implementation work.", "Use `skills/coherence/SKILL.md` before proposing file updates.", "Ask the founder to confirm the MVP validation scope before writing.", "After confirmation, offer the handoff to Product Ops when the founder wants delivery scope or Epic planning."],
      guidedConversation: ["Start by restating the confirmed Strategy Baseline.", "Ask only for missing constraints or validation choices.", "When the founder wants speed, prefer the smallest artifact that can teach the business something real.", "Make the handoff explicit: Strategy validates what should be tried; Product Ops turns confirmed scope into delivery work."],
      outputs: ["MVP Validation Scope", "Business thesis", "MVP slice", "Success signals", "Pivot signals", "MVP Validation Sequence", "Product Ops handoff recommendation"],
      filesToUpdate: ["../knowledge/mvp-validation-scope.md", "../knowledge/validation-notes.md"]
    }
  ];
