import type { PlaybookDefinition } from "../../../../types.js";

export const strategyBusinessPlaybooks: PlaybookDefinition[] = [
    {
      slug: "business-foundation",
      title: "Business Foundation",
      purpose: "Transformar contexto bruto do founder em identidade, princípios, modelo operacional e business model inicial usando perguntas guiadas e simples.",
      useWhen: ["o founder está iniciando o LeanOS e ainda não existe Business Foundation confiável", "missão, princípios, modelo operacional ou business model bloqueiam decisões de Product", "Strategy Product precisa entender receita, canal, promessa ou limites antes de calibrar uma ideia"],
      beforeActing: ["../AGENT.md", "../area.yaml", "../../../.leanos/standard/foundation/guided-conversation.md"],
      inputs: ["../knowledge/profile.md", "../knowledge/mission.md", "../knowledge/vision.md", "../knowledge/principles.md", "../knowledge/operating-model.md", "../knowledge/business-model-canvas.md", "../knowledge/decision-log.md"],
      steps: ["Carregue o AGENT de Business e a role Business Strategist.", "Leia `.leanos/standard/foundation/guided-conversation.md` e conduza uma pergunta por vez.", "Não aceite entrevista aberta como padrão; ofereça opções numeradas e deixe o founder responder com número.", "Use `skills/business-identity/SKILL.md` para cliente inicial, promessa, propósito, princípio e não-promessas.", "Use `skills/business-model/SKILL.md` quando receita, canal ou entrega forem necessários para destravar Product.", "Use `skills/operating-model/SKILL.md` quando a colaboração founder/IA estiver indefinida.", "Monte um Business Foundation Snapshot com status e confiança antes de propor escrita.", "Registre decisões e perguntas abertas.", "Proponha atualizações de arquivo e aguarde confirmação antes de escrever."],
      guidedConversation: ["Faça uma pergunta por vez; não transforme Business Foundation em formulário longo.", "`Quem vamos ajudar primeiro?` Opções: pessoas/consumidores finais; pequenas empresas/equipes; empresas maiores/área específica; profissionais independentes/criadores; ainda não sei, recomende.", "`Qual mudança o negócio promete?` Opções: economizar tempo; reduzir custo, erro ou risco; aumentar receita, vendas ou leads; organizar operação e decisões; melhorar suporte ou relacionamento.", "`Por que o negócio deve existir?` Opções: resolver uma dor frequente; tornar algo caro/lento acessível; automatizar trabalho repetitivo; dar clareza para decidir melhor; criar uma nova forma de entregar valor.", "`Como o negócio pretende ganhar dinheiro?` Opções: assinatura; serviço/setup/implantação; comissão ou success fee; uso/créditos; ainda é hipótese.", "`Qual princípio deve guiar decisões difíceis?` Opções: simplicidade para o cliente; segurança e privacidade primeiro; velocidade com escopo pequeno; qualidade acima de volume; atendimento humano quando a IA não for suficiente.", "`O que não devemos prometer agora?` Opções: resultado financeiro garantido; substituição total de humanos; automação 100% sem revisão; integrações complexas no MVP; escala enterprise agora.", "`Como founder e IA devem operar?` Opções: IA propõe, founder decide; IA executa tarefas aprovadas; IA monitora e sugere próximos passos; IA automatiza rotinas de baixo risco; ainda não definido."],
      outputs: ["Business Foundation Snapshot", "business_foundation_status: draft", "confidence: founder-assumption", "Mission/vision/principles proposal", "Business model canvas proposal", "Operating model proposal", "Decision log entries"],
      filesToUpdate: ["../knowledge/profile.md", "../knowledge/mission.md", "../knowledge/vision.md", "../knowledge/principles.md", "../knowledge/operating-model.md", "../knowledge/business-model-canvas.md", "../knowledge/decision-log.md"],
      redLines: ["Não faça pergunta aberta como caminho principal.", "Não registre respostas iniciais como validated sem evidência.", "Não invente pricing, canais ou claims de mercado.", "Não atualize arquivos sem confirmação explícita."]
    }
  ];
