import type { PlaybookDefinition } from "../../../../types.js";

export const operationsProductOpsPlaybooks: PlaybookDefinition[] = [
    {
      slug: "delivery-scope-planning",
      title: "Planejamento De Escopo De Delivery",
      purpose: "Transformar um item de MVP backlog, roadmap, backlog ou candidato de delivery em escopo de delivery confirmado sem criar Epics, issues ou código.",
      inputs: ["Item de MVP backlog, item de roadmap, item de backlog ou candidato de delivery", "Brief de produto", "Status de backlog e roadmap", "Escopo de delivery existente", "Escopo do MVP quando `scope_type` for MVP", "Restrições conhecidas"],
      steps: ["Leia o AGENT de Product Ops e escolha a role Product Owner.", "Leia o item de delivery, o brief de produto e o escopo de delivery atual.", "Use `skills/define-delivery-scope/SKILL.md` para decidir se o item vira escopo de delivery.", "Defina `scope_type`, `milestone` e `release_goal` somente depois que o founder confirmar.", "Defina não objetivos, dependências e aplicabilidade para Design, Security e DevOps.", "Se `scope_type` for MVP, mapeie a decisão para arquivos de MVP.", "Proponha atualizações de arquivo e aguarde confirmação antes de escrever."],
      outputs: ["Proposta de escopo de delivery", "scope_type", "milestone", "release_goal", "Não objetivos", "Aplicabilidade de Design/Security/DevOps", "Próxima rota recomendada"],
      filesToUpdate: ["Atualize `../knowledge/delivery-scope.md` somente após confirmação explícita.", "Atualize `../mvp/scope.md`, `../mvp/prd.md`, `../mvp/non-goals.md` e `../mvp/acceptance-criteria.md` somente quando `scope_type` for MVP e o founder confirmar.", "Não atualize GitHub a partir deste playbook."]
    },
    {
      slug: "mvp-backlog-planning",
      title: "Planejamento Do MVP Backlog",
      purpose: "Transformar o MVP Validation Scope aprovado pelo founder em itens de MVP backlog de Product Ops antes de qualquer Epic ou Feature existir.",
      useWhen: ["o founder aprovou o plano de validação do MVP", "Strategy Product está pronto para fazer handoff do MVP Validation Scope para Product Ops", "Product Ops precisa registrar itens candidatos e aprovados do MVP antes do planejamento de Epic"],
      beforeActing: ["../AGENT.md", "../knowledge/overview.md", "../knowledge/work-taxonomy.md", "../knowledge/mvp-decision-gate.md", "../knowledge/delivery-scope.md", "../mvp/backlog.md", "../mvp/scope.md", "../mvp/prd.md", "../../../strategy/product/AGENT.md", "../../../strategy/product/knowledge/brief.md", "../../../strategy/product/knowledge/problem.md", "../../../strategy/product/knowledge/icp.md", "../../../strategy/product/knowledge/value-proposition.md", "../../../strategy/product/knowledge/mvp-validation-scope.md"],
      inputs: ["MVP Validation Scope aprovado pelo founder", "Brief de produto", "Problema", "ICP", "Proposta de valor", "Modelo de negócio ou premissa", "MVP backlog existente", "MVP Decision Gate"],
      steps: ["Leia o AGENT de Product Ops e escolha a role Product Owner.", "Leia o MVP Validation Scope de Strategy Product e confirme que foi aprovado pelo founder.", "Carregue `../knowledge/mvp-decision-gate.md` para manter riscos de Value, Usability, Feasibility e Business Viability visíveis.", "Traduza o plano de validação aprovado em itens de MVP backlog.", "Classifique cada item como candidate, approved_for_mvp, needs_discovery, needs_specialist_check, deferred ou not_now.", "Registre quais itens estão aprovados para criação de Epic e quais permanecem estacionados.", "Identifique checks de Design, Security, Engineering ou DevOps somente quando afetarem um item que entra no MVP backlog.", "Explique a proposta de MVP backlog em linguagem amigável ao founder.", "Proponha atualizações e aguarde confirmação antes de escrever.", "Após confirmação, pergunte se o founder quer transformar um item aprovado em Epic agora ou continuar refinando o MVP backlog."],
      guidedConversation: ["Pergunte somente quando o plano aprovado de Strategy não tiver detalhe suficiente para criar itens de backlog.", "Prefira aprovação em pacote para a proposta de backlog, depois confirmação item a item somente antes da criação de Epic.", "Não reabra discovery de Strategy salvo se o plano de validação estiver inconsistente."],
      gates: ["MVP Validation Scope de Strategy Product existe.", "Founder aprovou o plano de validação do MVP.", "Cada item de backlog tem motivo de validação ou outcome de produto.", "Itens que precisam de especialistas são marcados antes da criação de Epic.", "Founder confirma antes de arquivos serem atualizados."],
      outputs: ["Proposta de MVP backlog", "Aprovados para MVP", "Itens candidatos", "Precisam de discovery", "Precisam de check especialista", "Itens adiados", "Primeiro candidato recomendado a Epic", "Perguntas abertas"],
      filesToUpdate: ["Atualize `../mvp/backlog.md` somente após confirmação explícita.", "Atualize `../knowledge/overview.md` quando o resumo de Product Ops mudar.", "Atualize `../knowledge/delivery-scope.md` somente após o founder confirmar uma decisão de escopo de delivery."],
      stopConditions: ["Pare se o MVP Validation Scope de Strategy Product estiver ausente.", "Pare se o founder não aprovou o plano de validação do MVP.", "Pare antes de criar Epics, Features, sync do GitHub, branches, PRs ou código.", "Pare se a solicitação virar trabalho de implementação antes de uma Epic existir."]
    },
    {
      slug: "delivery-item-to-epic",
      title: "Item De Delivery Para Epic",
      purpose: "Transformar um item aprovado de MVP backlog, roadmap, backlog ou escopo de delivery somente em uma Epic local do LeanOS antes de qualquer Feature, sync do GitHub, branch, código ou PR existir.",
      useWhen: ["o founder pede para criar uma Epic para um item aprovado", "um item de MVP backlog está aprovado para criação de Epic", "um item de roadmap ou backlog tem contexto de produto suficiente para virar trabalho de delivery", "um item de escopo de delivery precisa de ownership local de Epic"],
      beforeActing: ["../AGENT.md", "../knowledge/overview.md", "../knowledge/work-taxonomy.md", "../knowledge/delivery-scope.md", "../knowledge/issue-readiness.md", "../mvp/backlog.md", "../epics/README.md", "../../../strategy/product/knowledge/brief.md", "../../../strategy/roadmap/knowledge/roadmap.md", "../../../strategy/roadmap/knowledge/backlog.md", "../../../.leanos/standard/templates/product/epic-template.md"],
      inputs: ["Item aprovado de MVP backlog, item de roadmap, item de backlog ou item de escopo de delivery", "Outcome de produto", "Valor para usuário/negócio", "Escopo conhecido", "Não objetivos", "Milestone ou objetivo de release", "Riscos conhecidos"],
      steps: ["Leia o AGENT de Product Ops e escolha a role Product Owner.", "Confirme que o item de delivery existe, está aprovado e tem contexto de produto suficiente.", "Use `skills/define-delivery-scope/SKILL.md` para decidir `scope_type`, `milestone` e `release_goal` como campos da Epic.", "Use `skills/shape-epic/SKILL.md` para definir outcome, owner, limite de escopo, não objetivos, riscos e prováveis grupos de Feature.", "Marque checks de Design, Security, Engineering ou DevOps conforme necessário somente quando puderem mudar a Epic.", "Se um check especialista ausente bloquear o limite da Epic, pare e peça para ativar ou rotear para essa área em vez de inventar a resposta.", "Explique a recomendação de Epic em linguagem amigável ao founder.", "Peça confirmação antes de criar ou atualizar a pasta local da Epic.", "Crie somente `../epics/<epic-slug>/epic.md` após confirmação; mantenha `../epics/README.md` como mapa da pasta e não crie trabalho downstream a partir deste playbook.", "Após confirmação, pergunte se o founder quer quebrar a Epic em Features com `epic-to-features` ou parar."],
      guidedConversation: ["Pergunte somente por contexto ausente que muda o limite da Epic.", "Prefira perguntas sim/não ou opções curtas ao decidir tipo de escopo, milestone ou não objetivos.", "Não faça perguntas especialistas em nome de áreas especialistas inativas."],
      gates: ["O item está aprovado para consideração de delivery.", "Outcome, usuário ou valor de negócio está claro.", "Escopo e não objetivos estão explícitos o suficiente para criar uma Epic.", "Checks especialistas bloqueantes são identificados antes da escrita.", "Founder confirma antes de arquivos serem atualizados.", "Este playbook cria somente uma Epic local e nenhum artefato downstream de delivery."],
      outputs: ["Recomendação de Epic", "Título da Epic local e slug da pasta", "Caminho do `epic.md` local", "Status de confirmação do founder", "scope_type", "milestone", "release_goal", "Outcome", "Escopo", "Não objetivos", "Riscos", "Prováveis grupos de Feature", "Checks especialistas", "Próxima rota recomendada"],
      filesToUpdate: ["Crie ou atualize `../epics/<epic-slug>/epic.md` somente após confirmação explícita.", "Atualize `../mvp/backlog.md` quando um item de MVP backlog mudar de status.", "Atualize `../knowledge/delivery-scope.md` ou `../knowledge/issue-readiness.md` somente quando o founder confirmar a decisão de delivery.", "Não crie arquivos de Feature, issues do GitHub, branches, mudanças de código-fonte ou PRs a partir deste playbook."],
      stopConditions: ["Pare se o item não existir ou não puder ser identificado.", "Pare se o item ainda for uma ideia solta.", "Pare se o founder não confirmar a criação da Epic.", "Pare antes de criar arquivos de Feature, issues do GitHub, branches, mudanças de código-fonte ou PRs."]
    },
    {
      slug: "epic-to-features",
      title: "Epic Para Features",
      purpose: "Quebrar uma Epic local do LeanOS em rascunhos de Feature de Product Ops com tarefas internas e critérios de prontidão antes de Engineering começar o trabalho.",
      useWhen: ["O founder pede para quebrar uma Epic em Features.", "Uma Epic local precisa de fatias de Feature.", "Product Ops precisa rascunhar arquivos de Feature e marcar lacunas de prontidão antes da implementação."],
      beforeActing: ["../AGENT.md", "../knowledge/overview.md", "../knowledge/work-taxonomy.md", "../knowledge/issue-readiness.md", "../knowledge/ready-to-develop.md", "../mvp/prd.md", "../mvp/scope.md", "../mvp/acceptance-criteria.md", "../epics/README.md", "../../../strategy/product/AGENT.md", "../../../strategy/roadmap/AGENT.md", "../../../.leanos/standard/templates/product/epic-template.md", "../../../.leanos/standard/templates/product/feature-template.md", "../../../.leanos/standard/templates/github/github-epic-template.md", "../../../.leanos/standard/templates/github/github-feature-template.md", "../../../.leanos/standard/templates/github/delivery-readiness-matrix-template.md"],
      inputs: ["Epic pai", "Milestone/ciclo atual", "Escopo do MVP", "PRD", "Critérios de aceite", "Delivery Readiness Matrix (DRM)", "Contexto conhecido de Design quando UX é afetada", "Contexto conhecido de Security quando superfícies sensíveis estão envolvidas", "Contexto conhecido de DevOps quando há impacto em delivery ou ambiente"],
      steps: ["Carregue o AGENT de Product Ops e escolha `roles/product-owner.role.md`.", "Carregue os templates locais de Epic e Feature de Product em `../../../.leanos/standard/templates/product/` antes de preparar qualquer issue do GitHub.", "Carregue `skills/shape-epic/SKILL.md` e confirme outcome da Epic, ownership da decisão, limite de escopo, não objetivos e Epic Readiness Matrix.", "Carregue `skills/write-feature-criteria/SKILL.md` e aplique a Delivery Readiness Matrix (DRM) no nível da Feature.", "Escreva critérios de Product Ops para cada Feature.", "Adicione tarefas internas dentro de cada Feature.", "Marque se a Feature precisará de implementation packet quando entrar em `feature-to-delivery-cycle`; não crie o packet durante Epic breakdown.", "Adicione critérios de Design somente quando UX, UI, fluxo, copy, acessibilidade, telas, estados, componentes ou interação forem afetados.", "Quando uma Feature depende de telas ou estados concretos, marque uma futura tarefa de Design para `operations/design/playbooks/screen-readiness.playbook.md`.", "Quando uma Feature depende de componentes de UI, marque se ela pode reutilizar um componente conhecido, adaptar um componente ou precisa de especificação futura de componente.", "Não crie a especificação completa do componente durante Feature Shaping; adicione uma tarefa de prontidão de Design para `operations/design/playbooks/component-readiness.playbook.md` quando uma especificação for necessária.", "Adicione critérios de Security somente quando dados, auth, permissões, privacidade, abuso, API, database, segredos, compliance, infraestrutura ou risco de código gerado por IA estiver envolvido.", "Adicione critérios de DevOps somente quando ambientes, CI/CD, deploy, observabilidade, GitHub Project, config ou prontidão de release forem afetados.", "Marque critérios de Engineering como expectativas de prontidão, não como aprovação de implementação.", "Marque dimensões não aplicáveis explicitamente e explique por quê.", "Prepare rascunhos locais de Feature e peça confirmação antes de criar arquivos locais de Feature ou qualquer escrita remota."],
      securityGate: ["Pare se a Epic tocar dados, auth, permissões, privacidade, abuso, API, database, segredos, compliance, infraestrutura ou risco de código gerado por IA e critérios de Security estiverem ausentes.", "Não rebaixe uma dimensão de Security para não aplicável sem explicar o motivo."],
      outputs: ["Resumo de prontidão da Epic", "Lista de rascunhos de Feature", "Checklist de tarefas internas por Feature", "Critérios DRM para cada Feature", "Critérios de Product Ops", "Necessidade futura de implementation packet por Feature", "Critérios de Design ou não aplicável com motivo", "Decisão de screen spec quando tela/estado/fluxo concreto é afetado", "Decisão de reuso/adaptação/spec de componente quando UI é afetada", "Tarefa de prontidão de Design para screen spec ou component spec quando necessária", "Expectativas de prontidão de Engineering", "Critérios de Security ou não aplicável com motivo", "Critérios de DevOps ou não aplicável com motivo", "Dependências e riscos", "Contexto ausente", "Pergunta de confirmação antes de criação remota de issue"],
      filesToUpdate: ["Crie ou atualize `../epics/<epic-slug>/<feature-slug>.md` somente após confirmação explícita.", "Não atualize GitHub diretamente pelo modelo.", "Não crie issues do GitHub, branches, mudanças de código ou PRs a partir deste playbook.", "Não atualize código-fonte.", "Atualize `../knowledge/issue-readiness.md` ou arquivos de MVP somente quando o usuário confirmar explicitamente uma mudança de escopo ou critérios."],
      stopConditions: ["Pare se a Epic pai estiver sem outcome, escopo ou não objetivos.", "Pare se critérios de Product Ops ou Engineering estiverem ausentes.", "Pare se critérios aplicáveis de Design, Security ou DevOps não puderem ser determinados.", "Pare antes de criar issues do GitHub, branches, mudanças de código ou PRs.", "Pare antes de qualquer escrita na API do GitHub até o usuário confirmar explicitamente."]
    },
    {
      slug: "delivery-readiness",
      title: "Prontidão De Delivery",
      purpose: "Confirmar que uma issue ou fatia de MVP tem clareza suficiente de produto, técnica e operacional para entrar em Engineering.",
      inputs: ["Issue ou fatia de MVP", "Overview de Product Ops", "Critérios Ready To Develop", "Escopo do MVP", "PRD", "Critérios de aceite", "Notas de prontidão de issue", "Contexto de Design e Security quando aplicável"],
      steps: ["Leia o AGENT de Product Ops e escolha a role Delivery Architect", "Revise escopo do MVP, PRD e critérios de aceite", "Identifique dependências e restrições técnicas", "Cheque aplicabilidade de Design e Security", "Capture somente decisões técnicas confirmadas", "Recomende ready, needs product shaping, needs design, needs security ou blocked"],
      outputs: ["Resultado de prontidão de delivery", "Critérios ausentes", "Dependências", "Aplicabilidade de Design ou Security", "Notas de decisão técnica", "Próxima ação recomendada"],
      filesToUpdate: ["Atualize `../knowledge/issue-readiness.md` ou `../knowledge/technical-decisions.md` somente após confirmação explícita."]
    }
  ];
