import type { PlaybookDefinition } from "../../../../types.js";

export const operationsProductOpsPlaybooks: PlaybookDefinition[] = [
    {
      slug: "delivery-scope-planning",
      title: "Delivery Scope Planning",
      purpose: "Turn an MVP backlog, roadmap, backlog or delivery candidate into confirmed delivery scope without creating epics, issues or code.",
      inputs: ["MVP backlog item, roadmap item, backlog item or delivery candidate", "Product brief", "Backlog and roadmap status", "Existing delivery scope", "MVP scope when scope_type is MVP", "Known constraints"],
      steps: ["Read Product Ops AGENT and choose the Product Owner role.", "Read the delivery item, product brief and current delivery scope.", "Use `skills/define-delivery-scope/SKILL.md` to decide whether the item becomes delivery scope.", "Set `scope_type`, `milestone` and `release_goal` only after the founder confirms.", "Define non-goals, dependencies and applicability for Design, Security and DevOps.", "If `scope_type` is MVP, map the decision to MVP files.", "Propose file updates and wait for confirmation before writing."],
      outputs: ["Delivery scope proposal", "scope_type", "milestone", "release_goal", "Non-goals", "Design/Security/DevOps applicability", "Recommended next route"],
      filesToUpdate: ["Update `../knowledge/delivery-scope.md` only after explicit confirmation.", "Update `../mvp/scope.md`, `../mvp/prd.md`, `../mvp/non-goals.md` and `../mvp/acceptance-criteria.md` only when `scope_type` is MVP and the founder confirms.", "Do not update GitHub from this playbook."]
    },
    {
      slug: "mvp-backlog-planning",
      title: "MVP Backlog Planning",
      purpose: "Turn the founder-approved Strategy Product MVP Validation Scope into Product Ops MVP backlog items before any Epic or Feature exists.",
      useWhen: ["the founder approved the MVP validation plan", "Strategy Product is ready to hand off MVP validation scope to Product Ops", "Product Ops needs to record candidate and approved MVP items before Epic planning"],
      beforeActing: ["../AGENT.md", "../knowledge/overview.md", "../knowledge/work-taxonomy.md", "../knowledge/mvp-decision-gate.md", "../knowledge/delivery-scope.md", "../mvp/backlog.md", "../mvp/scope.md", "../mvp/prd.md", "../../../strategy/product/AGENT.md", "../../../strategy/product/knowledge/brief.md", "../../../strategy/product/knowledge/problem.md", "../../../strategy/product/knowledge/icp.md", "../../../strategy/product/knowledge/value-proposition.md", "../../../strategy/product/knowledge/mvp-validation-scope.md"],
      inputs: ["Founder-approved MVP Validation Scope", "Product brief", "Problem", "ICP", "Value proposition", "Business model or assumption", "Existing MVP backlog", "MVP Decision Gate"],
      steps: ["Read Product Ops AGENT and choose the Product Owner role.", "Read Strategy Product MVP Validation Scope and confirm it was approved by the founder.", "Load `../knowledge/mvp-decision-gate.md` to keep Value, Usability, Feasibility and Business Viability risks visible.", "Translate the approved validation plan into MVP backlog items.", "Classify each item as candidate, approved_for_mvp, needs_discovery, needs_specialist_check, deferred or not_now.", "Record which items are approved for Epic creation and which remain parked.", "Identify Design, Security, Engineering or DevOps checks only when they affect an item entering the MVP backlog.", "Explain the MVP backlog proposal in founder-friendly language.", "Propose updates and wait for confirmation before writing.", "After confirmation, ask whether the founder wants to transform an approved item into an Epic now or keep refining the MVP backlog."],
      guidedConversation: ["Ask only when the approved Strategy plan lacks enough detail to create backlog items.", "Prefer package approval for the backlog proposal, then item-by-item confirmation only before Epic creation.", "Do not re-open Strategy discovery unless the validation plan is inconsistent."],
      gates: ["Strategy Product MVP Validation Scope exists.", "Founder approved the MVP validation plan.", "Each backlog item has a validation reason or product outcome.", "Items needing specialists are marked before Epic creation.", "Founder confirms before files are updated."],
      outputs: ["MVP backlog proposal", "Approved for MVP", "Candidate items", "Needs discovery", "Needs specialist check", "Deferred items", "Recommended first Epic candidate", "Open questions"],
      filesToUpdate: ["Update `../mvp/backlog.md` only after explicit confirmation.", "Update `../knowledge/overview.md` when Product Ops summary changes.", "Update `../knowledge/delivery-scope.md` only after founder confirms a delivery-scope decision."],
      stopConditions: ["Stop if Strategy Product MVP Validation Scope is missing.", "Stop if the founder has not approved the MVP validation plan.", "Stop before creating Epics, Features, GitHub sync, branches, PRs or code.", "Stop if the request becomes implementation work before an Epic exists."]
    },
    {
      slug: "delivery-item-to-epic",
      title: "Delivery Item To Epic",
      purpose: "Turn an approved MVP backlog, roadmap, backlog or delivery-scope item into only a local LeanOS Epic before any Feature, GitHub sync, branch, code or PR exists.",
      useWhen: ["the founder asks to create an Epic for an approved item", "an MVP backlog item is approved for Epic creation", "a roadmap or backlog item has enough product context to become delivery work", "a delivery-scope item needs local Epic ownership"],
      beforeActing: ["../AGENT.md", "../knowledge/overview.md", "../knowledge/work-taxonomy.md", "../knowledge/delivery-scope.md", "../knowledge/issue-readiness.md", "../mvp/backlog.md", "../epics/README.md", "../../../strategy/product/knowledge/brief.md", "../../../strategy/roadmap/knowledge/roadmap.md", "../../../strategy/roadmap/knowledge/backlog.md", "../../../ai-standard/templates/product/epic-template.md"],
      inputs: ["Approved MVP backlog item, roadmap item, backlog item or delivery-scope item", "Product outcome", "User/business value", "Known scope", "Non-goals", "Milestone or release goal", "Known risks"],
      steps: ["Read Product Ops AGENT and choose the Product Owner role.", "Confirm the delivery item exists, is approved and has enough product context.", "Use `skills/define-delivery-scope/SKILL.md` to decide `scope_type`, `milestone` and `release_goal` as Epic fields.", "Use `skills/shape-epic/SKILL.md` to define outcome, owner, scope boundary, non-goals, risks and likely feature groups.", "Mark Design, Security, Engineering or DevOps checks as needed only when they can change the Epic.", "If a missing specialist check blocks the Epic boundary, stop and ask to activate or route to that area instead of inventing the answer.", "Explain the Epic recommendation in founder-friendly language.", "Ask for confirmation before creating or updating the local Epic folder.", "Create only the local Epic README after confirmation; do not create downstream work from this playbook.", "After confirmation, ask whether the founder wants to break the Epic into Features with `epic-to-features` or stop."],
      guidedConversation: ["Ask only for missing context that changes the Epic boundary.", "Prefer yes/no or short option questions when deciding scope type, milestone or non-goals.", "Do not ask specialist questions on behalf of inactive specialist areas."],
      gates: ["The item is approved for delivery consideration.", "Outcome, user or business value is clear.", "Scope and non-goals are explicit enough to create an Epic.", "Blocking specialist checks are identified before writing.", "Founder confirms before files are updated.", "This playbook creates only a local Epic and no downstream delivery artifacts."],
      outputs: ["Epic recommendation", "Local Epic title and folder slug", "Local Epic README path", "Founder confirmation status", "scope_type", "milestone", "release_goal", "Outcome", "Scope", "Non-goals", "Risks", "Likely feature groups", "Specialist checks", "Recommended next route"],
      filesToUpdate: ["Create or update `../epics/<epic-slug>/README.md` only after explicit confirmation.", "Update `../mvp/backlog.md` when an MVP backlog item changes status.", "Update `../knowledge/delivery-scope.md` or `../knowledge/issue-readiness.md` only when the founder confirms the delivery decision.", "Do not create Feature files, GitHub issues, branches, source code changes or PRs from this playbook."],
      stopConditions: ["Stop if the item does not exist or cannot be identified.", "Stop if the item is still a loose idea.", "Stop if the founder does not confirm Epic creation.", "Stop before creating Feature files, GitHub issues, branches, source code changes or PRs."]
    },
    {
      slug: "epic-to-features",
      title: "Epic To Features",
      purpose: "Break a local LeanOS Epic into Product Ops Feature drafts with internal tasks and readiness criteria before Engineering starts work.",
      useWhen: ["The founder asks to break an epic into features.", "A local Epic needs feature slices.", "Product Ops needs to draft Feature files and mark readiness gaps before implementation."],
      beforeActing: ["../AGENT.md", "../knowledge/overview.md", "../knowledge/work-taxonomy.md", "../knowledge/issue-readiness.md", "../knowledge/ready-to-develop.md", "../mvp/prd.md", "../mvp/scope.md", "../mvp/acceptance-criteria.md", "../epics/README.md", "../../../strategy/product/AGENT.md", "../../../strategy/roadmap/AGENT.md", "../../../ai-standard/templates/product/epic-template.md", "../../../ai-standard/templates/product/feature-template.md", "../../../ai-standard/templates/github/github-epic-template.md", "../../../ai-standard/templates/github/github-feature-template.md", "../../../ai-standard/templates/github/delivery-readiness-matrix-template.md"],
      inputs: ["Parent Epic", "Milestone/current cycle", "MVP scope", "PRD", "Acceptance criteria", "Delivery Readiness Matrix (DRM)", "Known Design context when UX is affected", "Known Security context when sensitive surfaces are involved", "Known DevOps context when delivery or environment impact exists"],
      steps: ["Load Product Ops AGENT and choose `roles/product-owner.role.md`.", "Load the local Product Epic and Feature templates from `../../../ai-standard/templates/product/` before preparing any GitHub issue.", "Load `skills/shape-epic/SKILL.md` and confirm the epic outcome, decision ownership, scope boundary, non-goals and Epic Readiness Matrix.", "Load `skills/write-feature-criteria/SKILL.md` and apply the Feature-level Delivery Readiness Matrix (DRM).", "Write Product Ops criteria for every Feature.", "Add internal tasks inside each Feature.", "Add Design criteria only when UX, UI, flow, copy, accessibility, screens, states, components or interaction is affected.", "When a Feature depends on UI components, mark whether it can reuse a known component, adapt one or needs a future component spec.", "Do not create the full component spec during Feature Shaping; add a Design readiness task for `operations/design/playbooks/component-readiness.playbook.md` when a spec is needed.", "Add Security criteria only when data, auth, permissions, privacy, abuse, API, database, secrets, compliance, infrastructure or AI-generated-code risk is involved.", "Add DevOps criteria only when environments, CI/CD, deploy, observability, GitHub Project, config or release readiness are affected.", "Mark Engineering criteria as readiness expectations, not implementation approval.", "Mark non-applicable dimensions explicitly and explain why.", "Prepare local Feature drafts and ask for confirmation before creating local Feature files or any remote write."],
      securityGate: ["Stop if the epic touches data, auth, permissions, privacy, abuse, API, database, secrets, compliance, infrastructure or AI-generated-code risk and Security criteria are missing.", "Do not downgrade a Security dimension to not applicable without explaining why."],
      outputs: ["Epic readiness summary", "Feature draft list", "Internal task checklist per feature", "DRM criteria for each feature", "Product Ops criteria", "Design criteria or not applicable with reason", "Component reuse/adaptation/spec decision when UI is affected", "Design readiness task for component spec when needed", "Engineering readiness expectations", "Security criteria or not applicable with reason", "DevOps criteria or not applicable with reason", "Dependencies and risks", "Missing context", "Confirmation question before remote issue creation"],
      filesToUpdate: ["Create or update `../epics/<epic-slug>/<feature-slug>.md` only after explicit confirmation.", "Do not update GitHub directly from the model.", "Do not create GitHub issues, branches, code changes or PRs from this playbook.", "Do not update source code.", "Update `../knowledge/issue-readiness.md` or MVP files only when the user explicitly confirms a scope or criteria change."],
      stopConditions: ["Stop if the parent epic is missing outcome, scope or non-goals.", "Stop if Product Ops or Engineering criteria are missing.", "Stop if applicable Design, Security or DevOps criteria cannot be determined.", "Stop before creating GitHub issues, branches, code changes or PRs.", "Stop before any GitHub API write until the user explicitly confirms."]
    },
    {
      slug: "delivery-readiness",
      title: "Delivery Readiness",
      purpose: "Confirm that an issue or MVP slice has enough product, technical and operational clarity to enter Engineering.",
      inputs: ["Issue or MVP slice", "Product Ops overview", "Ready To Develop criteria", "MVP scope", "PRD", "Acceptance criteria", "Issue readiness notes", "Design and Security context when applicable"],
      steps: ["Read Product Ops AGENT and choose the Delivery Architect role", "Review MVP scope, PRD and acceptance criteria", "Identify dependencies and technical constraints", "Check Design and Security applicability", "Capture only confirmed technical decisions", "Recommend ready, needs product shaping, needs design, needs security or blocked"],
      outputs: ["Delivery readiness result", "Missing criteria", "Dependencies", "Design or Security applicability", "Technical decision notes", "Recommended next action"],
      filesToUpdate: ["Update `../knowledge/issue-readiness.md` or `../knowledge/technical-decisions.md` only after explicit confirmation."]
    }
  ];
