import type { SkillDefinition } from "../../../../types.js";

export const operationsProductOpsSkills: SkillDefinition[] = [
    {
      slug: "delivery-scope",
      title: "Definir Escopo De Delivery",
      purpose: "Decidir se um item de MVP backlog, roadmap ou candidato de delivery vira escopo concreto de entrega e registrar scope_type, milestone e release_goal.",
      useWhen: ["um item de MVP backlog pode virar Epic", "um item de roadmap pode entrar na próxima entrega", "o founder pergunta se algo entra no escopo de MVP, release, beta ou experimento", "um item de delivery precisa de shaping de Product Ops antes da criação de Epic"],
      requiredContext: ["../knowledge/delivery-scope.md", "../mvp/backlog.md", "../../../strategy/roadmap/knowledge/roadmap.md", "../../../strategy/roadmap/knowledge/backlog.md", "../../../strategy/product/knowledge/brief.md"],
      inputs: ["Item de MVP backlog, item de roadmap ou candidato de delivery", "Outcome de produto", "Valor para usuário/negócio", "Nível de evidência", "Tipo de escopo", "Milestone", "Objetivo de release", "Restrições conhecidas"],
      process: ["Restate the delivery item and outcome.", "Confirm whether the item is ready for delivery scope or should remain in MVP backlog, roadmap or backlog.", "Choose scope_type: MVP, Release, Experiment, Beta or Internal.", "Define milestone and release_goal.", "Identify non-goals, dependencies and risks.", "Check Design, Security and DevOps applicability.", "Proponha atualizações de arquivo e aguarde confirmação antes de escrever."],
      checks: ["O item de delivery está claro o suficiente para escopo.", "O scope_type está explícito.", "Milestone e release_goal não foram inventados silenciosamente.", "Não objetivos estão visíveis.", "O item não é enviado ao GitHub antes da confirmação do escopo de delivery."],
      outputs: ["Recomendação de escopo de delivery", "scope_type", "milestone", "release_goal", "Não objetivos", "Dependências", "Próxima recomendação de workflow"],
      filesToUpdate: ["Atualize `../knowledge/delivery-scope.md` somente após confirmação explícita.", "Atualize `../mvp/scope.md` somente quando `scope_type` for MVP e o founder confirmar.", "Não crie issues do GitHub a partir desta skill."],
      redLines: ["Não trate prioridade de roadmap como compromisso de delivery.", "Não marque um item como MVP só porque ele é importante.", "Não crie epics nem features nesta etapa."]
    },
    {
      slug: "acceptance-criteria",
      title: "Escrever Critérios De Aceite",
      purpose: "Definir critérios de aceite testáveis de Product Ops para trabalho de MVP, Epic ou Feature sem transformar critérios em instruções de implementação.",
      useWhen: ["trabalho de MVP, Epic ou Feature precisa de critérios de conclusão", "um item de delivery tem expectativa de passa/falha pouco clara", "Product Ops precisa de critérios de aceite antes de prontidão ou handoff", "critérios existentes misturam escopo, detalhes de implementação e outcomes"],
      requiredContext: ["../AGENT.md", "../knowledge/work-taxonomy.md", "../mvp/prd.md", "../mvp/scope.md", "../mvp/acceptance-criteria.md", "../epics/README.md", "../../../strategy/product/knowledge/brief.md"],
      inputs: ["Item de delivery, Epic ou Feature", "Outcome de usuário ou cliente", "Escopo do MVP ou escopo de delivery", "Não objetivos conhecidos", "PRD ou critérios de aceite existentes", "Aplicabilidade conhecida de Design, Security, DevOps ou Engineering"],
      process: ["Reafirme o outcome pretendido e quem se beneficia.", "Separe comportamento dentro do escopo de não objetivos e ideias de implementação.", "Escreva critérios observáveis com teste claro de passa/falha.", "Cubra caminho feliz, estados de borda, erros, permissões, dados e copy somente quando aplicável.", "Mapeie critérios para dimensões de prontidão de Product Ops, Design, Engineering, Security ou DevOps.", "Marque contexto ausente explicitamente e pergunte antes de atualizar arquivos locais de critérios."],
      checks: ["Cada critério descreve comportamento observável ou outcome concreto de negócio/usuário.", "Cada critério é testável com resultado passa/falha.", "Critérios não prescrevem detalhes de implementação, estrutura de código ou escolha de ferramentas.", "Não objetivos e expectativas fora de escopo estão visíveis.", "Dimensões aplicáveis de Design, Security, DevOps e Engineering estão incluídas ou marcadas como não aplicáveis com motivo."],
      outputs: ["Lista de critérios de aceite", "Notas de validação passa/falha", "Não objetivos", "Dimensões de prontidão tocadas", "Contexto ausente", "Atualizações de arquivo recomendadas"],
      filesToUpdate: ["Atualize `../mvp/acceptance-criteria.md` somente após confirmação explícita.", "Atualize um arquivo local de Epic ou Feature somente após o founder confirmar os critérios escopados.", "Não atualize GitHub, branches, código-fonte ou PRs a partir desta skill."],
      redLines: ["Não escreva instruções de implementação, tarefas de código ou escolhas de arquitetura como critérios de aceite.", "Não expanda escopo ao escrever critérios.", "Não aceite critérios vagos que não podem ser testados.", "Não crie Epics, arquivos de Feature, issues do GitHub, branches, código ou PRs."]
    },
    {
      slug: "delivery-coherence",
      title: "Checar Coerência De Delivery",
      purpose: "Checar se escopo de delivery, contexto do MVP, intenção de roadmap e critérios de aceite estão alinhados antes de Product Ops avançar o trabalho.",
      useWhen: ["escopo de delivery pode não combinar com Strategy ou escopo do MVP", "uma Epic, Feature ou item de backlog parece inconsistente", "critérios conflitam com roadmap, PRD, não objetivos ou prontidão", "Product Ops precisa de um gate de coerência antes de Epic, Feature ou handoff para Engineering"],
      requiredContext: ["../AGENT.md", "../knowledge/work-taxonomy.md", "../knowledge/delivery-scope.md", "../knowledge/issue-readiness.md", "../mvp/backlog.md", "../mvp/prd.md", "../mvp/scope.md", "../mvp/acceptance-criteria.md", "../../../strategy/product/knowledge/brief.md", "../../../strategy/roadmap/knowledge/roadmap.md"],
      inputs: ["Escopo de delivery, Epic, Feature ou item de backlog", "Outcome de produto", "Escopo do MVP", "PRD", "Critérios de aceite", "Contexto de roadmap ou backlog", "Riscos, dependências e não objetivos conhecidos"],
      process: ["Reafirme o trabalho proposto e o outcome declarado.", "Compare o trabalho com brief de Strategy Product, escopo do MVP, PRD e critérios de aceite.", "Cheque se prioridade de roadmap ou backlog está sendo tratada como compromisso de delivery.", "Identifique contradições, critérios ausentes, escopo grande demais e dependências sem dono.", "Classifique o resultado como coerente, precisa de shaping, bloqueado ou fora de escopo.", "Recomende a menor próxima rota de Product Ops sem reescrever escopo silenciosamente."],
      checks: ["O trabalho mapeia para um outcome aprovado de produto ou delivery.", "Escopo do MVP, PRD, critérios e não objetivos não se contradizem.", "Prioridade de roadmap não é tratada como aprovação de implementação.", "Dependências e checks especialistas estão visíveis.", "A recomendação nomeia o próximo dono ou condição de parada."],
      outputs: ["Resultado de coerência", "Contexto alinhado", "Contradições", "Critérios ausentes", "Riscos de escopo", "Próxima rota recomendada"],
      filesToUpdate: ["Atualize `../knowledge/issue-readiness.md` somente após confirmação explícita.", "Atualize `../knowledge/delivery-scope.md` somente após o founder confirmar uma decisão de escopo.", "Não atualize roadmap, GitHub, branches, código-fonte ou PRs a partir desta skill."],
      redLines: ["Não reescreva escopo de delivery silenciosamente para fazê-lo parecer coerente.", "Não promova prioridade de roadmap para prontidão de delivery.", "Não esconda contradições ou checks especialistas ausentes.", "Não crie Epics, Features, issues do GitHub, branches, código ou PRs."]
    },
    {
      slug: "shape-epic",
      title: "Modelar Epic",
      purpose: "Transformar um item de delivery aprovado em limite de escopo de Epic pronto para implementação antes da criação de Features.",
      useWhen: ["um item aprovado do MVP backlog precisa virar Epic local do LeanOS", "um item de roadmap precisa virar Epic local do LeanOS", "uma Epic existente precisa de clareza suficiente para ser quebrada", "o time precisa confirmar outcome, escopo e não objetivos antes de Features ou sync remoto"],
      requiredContext: ["../AGENT.md", "../knowledge/overview.md", "../knowledge/work-taxonomy.md", "../knowledge/issue-readiness.md", "../knowledge/ready-to-develop.md", "../mvp/backlog.md", "../mvp/prd.md", "../mvp/scope.md", "../epics/README.md", "../../../strategy/product/knowledge/brief.md", "../../../strategy/roadmap/knowledge/roadmap.md", "../../../.leanos/standard/templates/product/epic-template.md", "../../../.leanos/standard/templates/github/delivery-readiness-matrix-template.md"],
      inputs: ["Item de delivery aprovado, item de MVP backlog ou item de roadmap", "Outcome de produto", "Escopo do MVP", "Não objetivos", "Milestone ou ciclo atual", "Dependências conhecidas"],
      process: ["Reafirme o outcome da Epic em uma frase.", "Confirme usuário, problema e valor de negócio.", "Identifique limites de escopo e não objetivos.", "Mapeie a Epic para escopo de delivery, PRD e milestone de roadmap.", "Use a Epic Readiness Matrix para decidir quais especialistas devem participar.", "Liste prováveis fatias de Feature sem criá-las ainda.", "Marque contexto ausente explicitamente em vez de inventá-lo."],
      checks: ["Outcome está claro.", "Escopo e não objetivos estão explícitos.", "A Epic pode ser quebrada sem perder intenção de produto.", "Inputs ausentes de Product, Design, Security, DevOps ou Engineering são declarados."],
      outputs: ["Resumo de prontidão da Epic", "Dono da decisão", "Limite de escopo", "Não objetivos", "Epic Readiness Matrix", "Prováveis grupos de Feature", "Contexto ausente", "Recomendação de prosseguir, refinar ou bloquear"],
      filesToUpdate: ["Atualize `../knowledge/issue-readiness.md` somente após confirmação explícita.", "Não atualize GitHub diretamente pelo modelo."],
      redLines: ["Não quebre um epic sem outcome ou escopo.", "Não invente critérios de aceite.", "Não contorne Design, Security ou DevOps quando seus critérios forem aplicáveis."]
    },
    {
      slug: "feature-criteria",
      title: "Escrever Critérios De Feature",
      purpose: "Aplicar a Delivery Readiness Matrix (DRM) para rascunhar Features prontas para implementação com tarefas internas.",
      useWhen: ["uma Epic está pronta para ser quebrada em Features", "Features precisam de critérios de Product, Design, Engineering, Security ou DevOps", "rascunhos de issue do GitHub precisam ser preparados antes de criação remota"],
      requiredContext: ["../AGENT.md", "../knowledge/work-taxonomy.md", "../knowledge/issue-readiness.md", "../knowledge/ready-to-develop.md", "../mvp/prd.md", "../mvp/acceptance-criteria.md", "../epics/README.md", "../../../growth/finance/knowledge/pricing.md when pricing or plan behavior is affected", "../../../.leanos/standard/templates/product/feature-template.md", "../../../.leanos/standard/templates/github/delivery-readiness-matrix-template.md", "../../../.leanos/standard/templates/github/github-feature-template.md"],
      inputs: ["Epic pronta", "Escopo do MVP", "PRD", "Critérios de aceite", "Delivery Readiness Matrix", "Contexto aplicável de Design, Security, DevOps e Engineering"],
      process: ["Write Product Ops criteria for every feature.", "Write Engineering criteria for every implementation-ready feature.", "Add internal tasks inside each feature.", "Mark whether the Feature will need an implementation packet when it enters `feature-to-delivery-cycle`.", "Add Design criteria only when the feature affects UX, UI, flow, copy, accessibility, screens, states, components or interaction.", "When Design is applicable, identify whether the feature needs screen-readiness, component-readiness or both.", "When Design is applicable, identify whether the feature can reuse a component, adapt a component or needs a new component spec.", "Não escreva a especificação completa do componente durante Feature Shaping; adicione uma tarefa de Design para `component-readiness` quando uma especificação for necessária.", "Add Pricing criteria only when the feature touches plans, prices, billing, checkout, paywall, subscription, trial, usage limit, quota or entitlement; use `../../../growth/finance/knowledge/pricing.md` as the source.", "Add Security criteria only when the feature touches data, auth, permissions, privacy, abuse, API, database, secrets, compliance, infrastructure or AI-generated-code risk.", "Add DevOps criteria only when the feature touches environments, CI/CD, deploy, observability, GitHub Project, config or release readiness.", "Mark non-applicable dimensions explicitly with a reason.", "Produce local feature drafts and ask for confirmation before remote creation."],
      checks: ["Toda Feature tem clareza de Product Ops e Engineering.", "Toda Feature tem tarefas internas.", "A necessidade de implementation packet está explícita para a próxima fase.", "Design está incluído ou explicitamente não aplicável.", "Features de UI identificam screen-readiness, component-readiness ou ambos.", "Features de UI identificam reuso, adaptação ou especificação obrigatória de componente.", "Features que precisam de novo componente incluem uma tarefa de Design antes do trabalho de Engineering.", "Pricing está incluído quando plano, preço, billing, paywall, trial, quota, limite ou entitlement é afetado.", "Security está incluído ou explicitamente não aplicável.", "DevOps está incluído ou explicitamente não aplicável.", "Dependências e riscos estão visíveis.", "Nenhuma escrita no GitHub acontece sem confirmação."],
      outputs: ["Lista de rascunhos de Feature", "Tabela DRM por Feature", "Checklist de tarefas internas por Feature", "Necessidade futura de implementation packet", "Decisão de screen-readiness quando tela/estado/fluxo concreto é afetado", "Decisão de prontidão de componente quando UI é afetada", "Decisão de Pricing/Plan readiness quando pricing é afetado", "Tarefa de Design para screen spec ou especificação de componente quando necessária", "Dependências", "Riscos", "Contexto ausente", "Prontidão do payload de rascunho", "Pergunta de confirmação"],
      filesToUpdate: ["Atualize `../knowledge/issue-readiness.md` somente após confirmação explícita.", "Não atualize GitHub diretamente pelo modelo."],
      redLines: ["Não crie features prontas para implementação sem critérios de Product Ops e Engineering.", "Não adicione critérios falsos de Design, Security ou DevOps quando não aplicável.", "Não chame a API do GitHub diretamente pelo modelo."]
    },
    {
      slug: "delivery-boundaries",
      title: "Definir Limites De Delivery",
      purpose: "Definir os limites mínimos de produto, técnicos e operacionais necessários para implementação segura sem criar artefatos prematuros de arquitetura.",
      useWhen: ["uma issue ou fatia de MVP precisa de prontidão de delivery", "Product Ops deve esclarecer limites de implementação antes de Engineering", "aplicabilidade de Design, Security, DevOps ou Engineering está incerta", "restrições técnicas ou riscos operacionais podem mudar o escopo de delivery"],
      requiredContext: ["../AGENT.md", "../knowledge/work-taxonomy.md", "../knowledge/issue-readiness.md", "../knowledge/ready-to-develop.md", "../knowledge/technical-decisions.md", "../mvp/prd.md", "../mvp/scope.md", "../mvp/acceptance-criteria.md", "../epics/README.md", "../../../growth/finance/knowledge/pricing.md when pricing or plan behavior is affected", "../../engineering/knowledge/implementation-rules.md"],
      inputs: ["Issue, Feature ou fatia de MVP", "Critérios de aceite", "Dependências conhecidas", "Restrições técnicas conhecidas", "Impacto em planos, pricing, billing, paywall ou entitlements", "Impacto em dados, auth, privacidade ou API", "Impacto em UI, fluxo, acessibilidade ou componente", "Impacto em ambiente, deploy ou observabilidade"],
      process: ["Reafirme a fatia e o limite de delivery em linguagem amigável ao founder.", "Separe limite de produto, limite técnico, limite operacional e não objetivos.", "Classifique Pricing/Plan applicability quando planos, preços, billing, checkout, paywall, subscription, trial, usage limit, quota ou entitlement aparecerem.", "Classifique aplicabilidade de Design, Security, DevOps e Engineering com motivo.", "Identifique dependências, premissas bloqueadas, necessidade de spike e lacunas de prontidão.", "Recomende ready, needs-product-shaping, needs-pricing, needs-design, needs-security, needs-devops, needs-engineering-spike ou blocked.", "Proponha a menor atualização local de knowledge e aguarde confirmação antes de escrever."],
      checks: ["O limite é estreito o suficiente para Engineering planejar com segurança.", "Pricing/Plan applicability está explícita e usa Growth Finance quando aplicável.", "Aplicabilidade de Design/Security/DevOps está explícita e fundamentada.", "Riscos de dados, auth, privacidade, API, ambiente e release não são pulados quando aplicáveis.", "Não objetivos evitam expansão de escopo.", "A recomendação não inventa detalhes de implementação."],
      outputs: ["Resumo do limite de delivery", "Aplicabilidade de Design/Security/DevOps", "Pricing/Plan applicability", "Expectativas de prontidão de Engineering", "Dependências", "Riscos e premissas bloqueadas", "Resultado de prontidão recomendado"],
      filesToUpdate: ["Atualize `../knowledge/issue-readiness.md` somente após confirmação explícita.", "Atualize `../knowledge/technical-decisions.md` somente quando existir uma decisão durável confirmada.", "Não atualize specs de Design, código de Engineering, issues do GitHub, branches ou PRs a partir desta skill."],
      redLines: ["Não crie artefatos de arquitetura nem código-fonte a partir desta skill.", "Não decida que Security, Design ou DevOps não se aplica sem motivo.", "Não transforme uma decisão de limite em aprovação de implementação.", "Não crie Epics, Features, issues do GitHub, branches, código ou PRs."]
    }
  ];
