import type { PlaybookDefinition } from "../../../../types.js";

export const operationsSecurityPlaybooks: PlaybookDefinition[] = [
    {
      slug: "security-foundation",
      title: "Security Foundation",
      purpose: "Create or refresh the Security Starter Baseline for an MVP product.",
      useWhen: ["initial security setup", "new MVP scope", "before implementation starts on sensitive surfaces"],
      beforeActing: ["../AGENT.md", "../knowledge/security-baseline.md", "../knowledge/threat-model.md", "../knowledge/access-control.md", "../knowledge/data-protection.md"],
      inputs: ["Product/MVP scope", "Data involved", "Auth model", "API/database surfaces", "Deployment target"],
      steps: ["Load Security Lead and Security Reviewer", "Review the security baseline red lines", "Identify whether access control, data protection, database, secrets or infra knowledge needs update", "Apply threat-modeling and access-control-review skills", "Produce baseline gaps and required next actions"],
      securityGate: ["Block implementation when auth, data ownership or sensitive data handling is unknown.", "Block deploy planning when database exposure, backups or rollback are unknown."],
      outputs: ["Resumo da baseline de Security", "Lacunas conhecidas", "Reviews obrigatórios", "Próxima ação segura"],
      filesToUpdate: ["Update `../knowledge/security-baseline.md`, `../knowledge/threat-model.md`, `../knowledge/access-control.md` or `../knowledge/data-protection.md` after explicit confirmation."],
      stopConditions: ["The request needs enterprise/compliance advice beyond MVP scope.", "The founder cannot confirm data/auth/ownership context.", "The model would need to invent product security facts."]
    },
    {
      slug: "pre-mvp-security-checklist",
      title: "Pre-MVP Security Checklist",
      purpose: "Run a lightweight security checklist before MVP implementation or issue breakdown.",
      useWhen: ["before MVP delivery-scope output becomes implementation work", "before creating implementation-ready issues", "when Product Ops asks for security criteria"],
      beforeActing: ["../AGENT.md", "../knowledge/security-baseline.md", "../knowledge/threat-model.md", "../knowledge/access-control.md", "../knowledge/data-protection.md"],
      inputs: ["MVP scope", "PRD", "User stories", "Acceptance criteria", "Known sensitive data", "Auth expectations"],
      steps: ["Load Security Reviewer", "Check baseline red lines", "Review access-control needs", "Review data-protection needs", "Review database and API risk if present", "List security acceptance criteria for Product Ops or Engineering"],
      securityGate: ["Stop if MVP includes private data but no server-side authorization criteria.", "Stop if sensitive data appears in logs/events/analytics requirements.", "Stop if tenant isolation is required but undefined."],
      outputs: ["Security checklist result", "Security acceptance criteria", "Required Product Ops/Engineering follow-up", "Blocked or safe-to-continue decision"],
      filesToUpdate: ["Update `../knowledge/security-baseline.md`, `../knowledge/threat-model.md`, `../knowledge/access-control.md`, `../knowledge/data-protection.md` or `../knowledge/database-security.md` after explicit confirmation."],
      stopConditions: ["MVP scope is unclear.", "Auth/data assumptions are missing.", "Required security criteria cannot be derived without founder confirmation."]
    },
    {
      slug: "security-automation-readiness",
      title: "Security Automation Readiness",
      purpose: "Decide which automated security checks are required, enabled, deferred or not applicable for this workspace.",
      useWhen: ["before production readiness", "before adding security CI workflows", "when stack and repository commands become clear", "when DevOps prepares release gates"],
      beforeActing: ["../AGENT.md", "../knowledge/security-automation.md", "../knowledge/security-baseline.md", "../../devops/AGENT.md", "../../devops/knowledge/ci-cd.md", ".github/leanos/security-automation.md"],
      inputs: ["Repository stack", "Package manager", "Build/test/lint commands", "Existing CI/CD", "Deployment target", "Security baseline", "Known GitHub/security features"],
      steps: ["Carregue Security Lead e Cloud Security Reviewer", "Use `skills/security-automation-readiness/SKILL.md`", "Classifique secret scanning, dependency audit, SAST/code scanning, IaC/config scanning e API/security checks", "Marque cada item como enable now, defer with reason ou not applicable", "Defina se cada check deve bloquear PR, bloquear deploy ou apenas alertar", "Peça confirmação antes de editar CI, configurações do GitHub ou configuração de scanner"],
      securityGate: ["Production deploy requires explicit security automation status.", "Block production readiness if secret scanning and dependency audit are neither enabled nor explicitly deferred with reason.", "Block creating scanner workflows when stack, package manager or commands are unknown."],
      outputs: ["Security automation readiness matrix", "Required security gates", "Deferred checks and reasons", "Suggested next file changes", "Safe-to-continue decision"],
      filesToUpdate: ["Update `../knowledge/security-automation.md` after explicit confirmation.", "Update `.github/leanos/security-automation.md` after explicit confirmation."],
      stopConditions: ["The repository stack is unknown.", "Build/test commands are unstable or missing.", "The request asks to enable scanners without understanding false-positive or CI impact.", "The request would require provider credentials or paid features not configured by the founder."]
    },
    {
      slug: "pre-deploy-security-review",
      title: "Pre-Deploy Security Review",
      purpose: "Act as a security quality gate before production or sensitive preview deployment.",
      useWhen: ["before production deploy", "before sensitive preview/staging deploy", "after security-sensitive PRs", "when DevOps asks for deploy readiness"],
      beforeActing: ["../AGENT.md", "../knowledge/security-baseline.md", "../knowledge/database-security.md", "../knowledge/secrets-management.md", "../knowledge/infra-hardening.md", "../knowledge/security-automation.md", "../../devops/AGENT.md"],
      inputs: ["Escopo de release", "PRs included", "Deployment target", "Plano de ambiente", "CI/CD status", "Backup/rollback plan", "Known vulnerabilities"],
      steps: ["Load Security Lead and the smallest specialist roles", "Review database exposure and backup/rollback", "Review server-side auth and authorization", "Review secrets/code/log exposure", "Review query safety", "Review CORS and rate limits", "Review vulnerable dependencies", "Review service account permissions", "Review security automation readiness status", "Return gate decision"],
      securityGate: ["Block deploy for public database.", "Block deploy for missing authorization.", "Block deploy for secrets in code.", "Block deploy for client-side token exposure.", "Block deploy for unsafe query.", "Block deploy for open CORS without justification.", "Block deploy for no rate limit on login or sensitive APIs.", "Block deploy for sensitive data in logs.", "Block deploy for no backup or rollback path.", "Block deploy for critical vulnerable dependency.", "Block deploy for over-permissive service account.", "Block deploy for missing tenant isolation.", "Block production readiness when security automation status is unknown."],
      outputs: ["Deploy security gate decision", "Blocking findings", "Required fixes", "Accepted residual risks", "Security reviewer role used"],
      filesToUpdate: ["Update `../knowledge/database-security.md`, `../knowledge/secrets-management.md`, `../knowledge/infra-hardening.md` or `../knowledge/incident-response.md` after explicit confirmation."],
      stopConditions: ["Any Security Gate blocker is present.", "Deploy target or environment cannot be identified.", "Backup/rollback path is unknown for production."]
    },
    {
      slug: "ai-app-security-review",
      title: "AI App Security Review",
      purpose: "Review AI app, agent, RAG or automation runtime risk before implementation, PR, launch or always-on operation.",
      useWhen: ["LLM input/output exists", "agent or AI feature can call tools", "RAG/vector DB retrieval exists", "customer data may enter prompts, logs, traces or embeddings", "prompt injection or cost/rate abuse can affect the product"],
      beforeActing: ["../AGENT.md", "../knowledge/security-baseline.md", "../knowledge/ai-app-security.md", "../knowledge/data-protection.md", "../knowledge/access-control.md", "../knowledge/secrets-management.md", "../../product-ops/knowledge/ready-to-develop.md", "../../engineering/knowledge/review-criteria.md"],
      inputs: ["Feature or AI agent scope", "LLM input/output surfaces", "Tool permissions", "RAG/vector DB sources and filters", "Customer data boundary", "Prompt injection exposure", "Cost/rate abuse expectation", "Accepted product risk when any"],
      steps: ["Load AI Security Engineer", "Use `skills/ai-runtime-security-review/SKILL.md`", "Map LLM input/output surfaces and mark untrusted boundaries", "Map tool permissions and external actions including writes, customer contact, payments, CRM, email, files and APIs", "Map RAG/vector DB retrieval sources, tenant filters, embedding storage and retrieval output handling", "Confirm customer data boundary across prompts, logs, traces, analytics and embeddings", "Review prompt injection and indirect prompt injection from user content, files, tickets, CRM, GitHub, docs or web pages", "Review cost/rate abuse, quota exhaustion and unattended automation loops", "Define mitigations, owners, residual risks and explicit Security gate decision", "Return pass, concerns, blocked or not applicable with evidence"],
      securityGate: ["Block when LLM input/output can drive writes or customer-visible decisions without validation.", "Block when tool permissions are broad, unexplained or not tied to an owner/gate.", "Block when RAG/vector DB can cross customer data boundary or tenant isolation.", "Block when prompt injection can trigger actions, data leakage or harmful output without mitigation.", "Block when cost/rate abuse can create runaway spend or service exhaustion without limits.", "Block when sensitive customer data enters prompts, logs, traces, embeddings or analytics without approved handling."],
      outputs: ["AI app security result", "LLM input/output risk summary", "Tool permissions decision", "RAG/vector DB boundary result", "Customer data boundary result", "Prompt injection findings", "Cost/rate abuse decision", "Required mitigations", "Safe-to-continue decision"],
      filesToUpdate: ["Update `../knowledge/ai-app-security.md` after explicit confirmation.", "Update `../knowledge/threat-model.md`, `../knowledge/data-protection.md`, `../knowledge/access-control.md` or `../knowledge/secrets-management.md` only when durable context changes.", "Update Product Ops Feature Security criteria only through Product Ops after confirmation."],
      stopConditions: ["AI feature scope is unclear.", "Tool permissions cannot be enumerated.", "Customer data boundary is unknown.", "RAG/vector DB sources or filters cannot be identified.", "Prompt injection exposure exists without mitigation.", "Cost/rate abuse is plausible and limits or owner are missing.", "The request would alter code, infra, secrets or permissions automatically."]
    },
    {
      slug: "api-security-review",
      title: "API Security Review",
      purpose: "Review an API endpoint or API change before implementation, PR or deploy.",
      useWhen: ["API endpoint changes", "auth-protected route changes", "public API behavior changes", "login or sensitive API work"],
      beforeActing: ["../AGENT.md", "../knowledge/threat-model.md", "../knowledge/access-control.md", "../knowledge/infra-hardening.md"],
      inputs: ["Endpoint", "Auth model", "Inputs/outputs", "Data sensitivity", "Rate limit/CORS expectations"],
      steps: ["Load Application Security Engineer", "Use api-security-review skill", "Check auth/authorization", "Check input validation and output leakage", "Check CORS and rate limits", "List fixes and not-applicable criteria"],
      securityGate: ["Block missing server-side authorization.", "Block sensitive API without rate limit.", "Block open CORS without justification.", "Block sensitive data leakage in response/errors/logs."],
      outputs: ["API security result", "Required fixes", "Security criteria for issue/PR", "Safe-to-continue decision"],
      filesToUpdate: ["Update `../knowledge/access-control.md`, `../knowledge/threat-model.md` or `../knowledge/infra-hardening.md` after explicit confirmation."],
      stopConditions: ["Endpoint ownership model is unknown.", "Auth model is undefined.", "Sensitive response shape is unclear."]
    },
    {
      slug: "database-security-review",
      title: "Database Security Review",
      purpose: "Review database changes for privacy, isolation, backup, query and permission risk.",
      useWhen: ["database schema/query/migration changes", "tenant isolation changes", "service-account permissions change", "data migration or destructive action"],
      beforeActing: ["../AGENT.md", "../knowledge/database-security.md", "../knowledge/data-protection.md", "../../engineering/knowledge/data-guidelines.md"],
      inputs: ["Data model", "Query or migration", "Data sensitivity", "Service account", "Backup/rollback"],
      steps: ["Load Data Protection Reviewer", "Use database-security-review skill", "Check production exposure", "Check SQL/query safety", "Check tenant isolation", "Check service-account permissions", "Check backup and rollback"],
      securityGate: ["Block public production database.", "Block SQL string concatenation.", "Block missing tenant isolation.", "Block no backup/rollback for risky data change."],
      outputs: ["Database security result", "Required fixes", "Migration/rollback notes", "Safe-to-continue decision"],
      filesToUpdate: ["Update `../knowledge/database-security.md` or `../knowledge/data-protection.md` after explicit confirmation."],
      stopConditions: ["Data sensitivity is unknown.", "Rollback cannot be defined.", "Tenant boundary is unclear."]
    },
    {
      slug: "secrets-rotation",
      title: "Secrets Rotation",
      purpose: "Guide safe secret rotation after leak, suspected exposure or credential change.",
      useWhen: ["secret leak or suspected exposure", "token appears in Git/logs/chat/screenshots", "credential owner changes", "incident response requires rotation"],
      beforeActing: ["../AGENT.md", "../knowledge/secrets-management.md", "../knowledge/incident-response.md", "../../devops/knowledge/environments.md"],
      inputs: ["Secret type", "Exposure location", "Affected environment", "Owner", "Access scope"],
      steps: ["Load Cloud Security Reviewer", "Classify exposure", "Contain or revoke exposed credential", "Rotate per environment", "Update consumers through secure provider", "Verify old secret no longer works", "Record follow-up without secret values"],
      securityGate: ["Treat any exposed production credential as compromised.", "Block continuing deploy if active leaked secret is still valid."],
      outputs: ["Rotation plan", "Containment status", "Verification steps", "Follow-up"],
      filesToUpdate: ["Update `../knowledge/secrets-management.md` or `../knowledge/incident-response.md` after explicit confirmation. Never write secret values."],
      stopConditions: ["The user asks to paste or store the secret value.", "The affected system cannot be identified.", "Revocation/rotation owner is unknown."]
    },
    {
      slug: "vulnerability-response",
      title: "Vulnerability Response",
      purpose: "Respond to critical vulnerable dependencies, insecure code paths or discovered weaknesses.",
      useWhen: ["critical dependency CVE", "security finding from PR/deploy review", "vulnerability alert", "post-release security issue"],
      beforeActing: ["../AGENT.md", "../knowledge/secure-coding.md", "../knowledge/incident-response.md", "../knowledge/security-baseline.md"],
      inputs: ["Finding", "Affected component", "Severity", "Exploitability", "Available fix/mitigation", "Release status"],
      steps: ["Load Application Security Engineer or Cloud Security Reviewer", "Classify severity and exposure", "Identify mitigation or patch", "Check tests and rollout risk", "Decide block/patch/monitor", "Record follow-up"],
      securityGate: ["Block release for critical vulnerable dependency without mitigation.", "Block release for exploitable auth/data exposure.", "Require founder/human review for dependency/security-sensitive changes."],
      outputs: ["Vulnerability response summary", "Mitigation plan", "Release decision", "Follow-up"],
      filesToUpdate: ["Update `../knowledge/incident-response.md` or `../knowledge/secure-coding.md` after explicit confirmation."],
      stopConditions: ["Severity cannot be determined.", "The fix requires auth, dependency, CI/CD or infra changes without human review.", "Exploitability is likely and containment is missing."]
    },
    {
      slug: "incident-response",
      title: "Incident Response",
      purpose: "Run a lightweight incident response path for leaks, abuse, outages or production security regressions.",
      useWhen: ["active security incident", "suspected leak", "abuse or suspicious behavior", "production security regression"],
      beforeActing: ["../AGENT.md", "../knowledge/incident-response.md", "../knowledge/security-baseline.md", "../knowledge/secrets-management.md"],
      inputs: ["Incident summary", "Affected users/data", "Timeline", "Evidence", "Current containment", "Owner"],
      steps: ["Load Security Lead", "Classify severity", "Contain or pause risky activity", "Rotate secrets when needed", "Preserve useful evidence", "Define recovery and verification", "Capture follow-up"],
      securityGate: ["Não continue deploy quando a contenção estiver incerta.", "Rotacione segredos expostos.", "Escale se exposição de dados sensíveis de cliente for possível."],
      outputs: ["Incident response summary", "Containment steps", "Recovery plan", "Verification plan", "Follow-up"],
      filesToUpdate: ["Update `../knowledge/incident-response.md` after explicit confirmation."],
      stopConditions: ["The user asks to delete evidence.", "Sensitive data exposure requires legal/compliance advice beyond MVP scope.", "Containment cannot be confirmed."]
    },
    {
      slug: "ai-generated-code-security-review",
      title: "AI Generated Code Security Review",
      purpose: "Review AI/vibe-coded changes for common agent-generated security failures.",
      useWhen: ["AI agent produced code", "Codex/Claude/Gemini/Copilot modified files", "tool/MCP access was used", "generated code changes dependencies, tests, auth, secrets, CI/CD or infra"],
      beforeActing: ["../AGENT.md", "../knowledge/security-baseline.md", "../knowledge/secure-coding.md", "../../engineering/AGENT.md"],
      inputs: ["Generated diff", "Issue/PR context", "Changed dependencies", "Changed tests", "Tool/MCP usage", "Touched files"],
      steps: ["Load Application Security Engineer", "Use ai-generated-code-security skill", "Check hallucinated or vulnerable dependencies", "Check prompt injection via issues, PRs, docs or logs", "Check unsafe shell commands and out-of-scope edits", "Check fabricated/deleted tests", "Check secrets/context leakage", "Check broad MCP/tool permissions", "Return safe-to-continue or blocked decision"],
      securityGate: ["Block hallucinated dependency.", "Block unsafe shell command from untrusted input.", "Block fabricated tests or deleted validation.", "Block auth, secrets, CI/CD, infra or dependency changes without human review.", "Block broad MCP/tool permissions without justification."],
      outputs: ["AI-generated-code security result", "Blocked items", "Required human review", "Safe-to-continue decision"],
      filesToUpdate: ["Update `../knowledge/secure-coding.md` or `../knowledge/security-baseline.md` only after explicit confirmation."],
      stopConditions: ["The diff scope does not match the issue.", "Tool permissions are broad and unexplained.", "The agent changed security-sensitive files without review."]
    }
  ];
